### ISSUE TITLE
Could you add some information on Readme how to create a config file?

### ISSUE THREAD

**Issue by GreenSage** [andrecasal/sftp-upload-on-change#2]
SFTP was a hard requirement for me to finally stick with Atom.io and I would love to be able to use the software. I'm searching all over how to create a config file for packages and I can't seem to find it. Sorry for this, first package beyond core. I've always just used Atom.io as an awesome text editor then uploaded with a seperate SFTP client.

EDIT: I do know that it gave me the green and blue boxes talking about it being created but...I don't have any idea where it's located at. My project is located at drive:/website but it's empty.

**Comment by andrecasal** [comment]
@GreenSage It wasn't clear for me what, exactly, your issue was.

Here's the steps to make this plugin work:
1. In Atom, press <kbd>shift</kbd>+<kbd>cmd</kbd>+<kbd>p</kbd> (macOS) and type `install package`
2. Then search for `sftp-upload-on-change` and click on the `install` button.
3. If sftp-upload-on-change doesn't find a configuration file in your root folder, it will ask you if you'd like to have one created for you. Choose yes.
4. Edit your config file accordingly with the following fields:
```
{
	"local": {
		"source"		: "c:/project/folder"
	},
	"remote": {
		"host"		: "ftp.domain.com",
		"port"		: "22",
		"user"		: "username",
		"password"	: "password",
		"target"		: "/home/user/website.com"
	}
}
```

Target is the remote folder where your files should be uploaded to, inside the server.

Let me know if this helped.
